version: "3.7"
services:

  app:
    build:
      context: ./src/app
      dockerfile: Dockerfile
    ports:
      - "80:8000"

  index:
    build:
      context: ./src/index
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ${PATH_TO_DATASET}
        target: /resources/dataset
      - type: bind
        source: ${PATH_TO_DUMP}
        target: /resources/dump
