version: "3.7"
services:

  app:
    image: slawiko/imalookalike-app:latest
    ports:
      - "80:8000"
    volumes:
      - type: bind
        source: ${PATH_TO_LANDMARKS}
        target: /resources/landmarks

  index:
    image: slawiko/imalookalike-index:latest
    user: root # FIXME
    volumes:
      - type: bind
        source: ${PATH_TO_DATASET}
        target: /resources/dataset
      - type: bind
        source: ${PATH_TO_DUMP}
        target: /resources/dump
